# Generated by Django 4.2.19 on 2025-03-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_activity_type_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default='', max_length=20),
        ),
    ]
