# Generated by Django 4.2.19 on 2025-03-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='us_phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
