# Generated by Django 4.2.19 on 2025-03-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_us_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='us_phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
